- name: Install kitty
  homebrew:
    name: kitty
    state: present

- name: Ensure the kitty config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/kitty"
    state: directory

- name: Copy kitty config
  copy:
    src: kitty.conf
    dest: "{{ ansible_env.HOME }}/.config/kitty/kitty.conf"
    backup: yes
